### ISSUE TITLE
Investigate: optimize Flickr data import

### ISSUE THREAD

**Issue by tjukanovt** [GispoCoding/geoviz-notebooks#33]
Currently the Flickr data import takes several minutes. It should be investigated if there is room for optimization. 

**Describe alternatives you've considered**
I came across [this QGIS plugin](https://github.com/samanbey/flickrdl/blob/master/flickrdl_dialog.py) which downloads Flickr data. There the page/bbox/temporal handling is slightly different. That script needs to be tested and investigated if it is more suitable for this purpose than the import script we have now.

**Comment by Rikuoja** [comment]
Optimized as much as possible now, methinks.
